import type { TroveMovieRecord } from './types';

export const TROVE_MEMBERS = ['Ren', 'Patio', 'Greg', 'Max', 'Quinn'] as const;

export const DUMMY_TREASURE_TROVE_MOVIES: TroveMovieRecord[] = [
  {
    id: 'tt1',
    title: 'The Godfather',
    yearReleased: 1972,
    originCountry: 'USA',
    runTime: 175,
    mpaaRating: 'R',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    ratings: { Ren: 10, Patio: 10, Greg: 10, Max: 9.5, Quinn: 10 },
    averageRating: 9.9,
  },
  {
    id: 'tt2',
    title: 'Tokyo Story',
    yearReleased: 1953,
    originCountry: 'Japan',
    runTime: 136,
    mpaaRating: 'NR',
    posterUrl: 'https://image.tmdb.org/t/p/w500/g2rxhG7Uq5D8QKzQ2AqGQh0f9fW.jpg',
    ratings: { Ren: 10, Patio: 9.5, Greg: 9.5, Max: 9.5, Quinn: 10 },
    averageRating: 9.7,
  },
  {
    id: 'tt3',
    title: 'Mulholland Drive',
    yearReleased: 2001,
    originCountry: 'USA',
    runTime: 147,
    mpaaRating: 'R',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oKyY4TFaLjQTgyX8oH1KuJnnxvB.jpg',
    ratings: { Ren: 9.5, Patio: 9.5, Greg: 9, Max: 9.5, Quinn: 10 },
    averageRating: 9.5,
  },
  {
    id: 'tt4',
    title: 'Spirited Away',
    yearReleased: 2001,
    originCountry: 'Japan',
    runTime: 125,
    mpaaRating: 'PG',
    posterUrl: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    ratings: { Ren: 9.5, Patio: 9, Greg: 9.5, Max: 9, Quinn: 9.5 },
    averageRating: 9.3,
  },
  {
    id: 'tt5',
    title: 'There Will Be Blood',
    yearReleased: 2007,
    originCountry: 'USA',
    runTime: 158,
    mpaaRating: 'R',
    posterUrl: 'https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg',
    ratings: { Ren: 9, Patio: 9.5, Greg: 9, Max: 9, Quinn: 9.5 },
    averageRating: 9.2,
  },
  {
    id: 'tt6',
    title: 'In the Mood for Love',
    yearReleased: 2000,
    originCountry: 'Hong Kong',
    runTime: 98,
    mpaaRating: 'PG',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iYypPT4OqTDX4DClqOQPEFm6mU.jpg',
    ratings: { Ren: 10, Patio: 9.5, Greg: 9, Max: 9.5, Quinn: 10 },
    averageRating: 9.6,
  },
  {
    id: 'tt7',
    title: 'Parasite',
    yearReleased: 2019,
    originCountry: 'South Korea',
    runTime: 132,
    mpaaRating: 'R',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    ratings: { Ren: 10, Patio: 9.5, Greg: 10, Max: 9, Quinn: 10 },
    averageRating: 9.7,
  },
  {
    id: 'tt8',
    title: 'Yi Yi',
    yearReleased: 2000,
    originCountry: 'Taiwan',
    runTime: 173,
    mpaaRating: 'NR',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8k6W6U8n8iWJ3xV9hQv0PjW2VJX.jpg',
    ratings: { Ren: 9.5, Patio: 9, Greg: 9.5, Max: 9, Quinn: 9.5 },
    averageRating: 9.3,
  },
];
