name: Backend Deployment Pipeline

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  push:
    branches:
      - main
      - backend-tests
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  backend_deployment_pipeline:
    runs-on: ubuntu-latest
    container:
      image: node:24.14.0-bookworm-slim
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - name: Say hello
        run: |
          echo "Hello world"
      - name: Install dependencies
        run: npm install
      # - name: Check style
      #   run: npm run eslint
