name: Deployment pipeline

on:
  push:
    branches:
      - main
      - backend-tests

jobs:
  backend_deployment_pipeline:
    runs-on: ubuntu-latest
    container:
      image: node:24.14.0-bookworm-slim
    steps:
      - uses: actions/checkout@v6
      - name: Say hello
        run: |
          echo "Hello world"
      # - name: Install dependencies
      #   run: npm install
      # - name: Check style
      #   run: npm run eslint
